# Live load is supported only in themes
# If you change anything besides themes
# You must restart shell

[clock]
# Check out https://strftime.org/ for help with formatting
format = "%x %H:%M"

[theme]
# Avaliable themes:
# "catppuccin-mocha" - Default theme
# "adwaita" - GNOME Adwaita Dark
# "everforest" - Greenish theme
# "gruvbox" - Orangeish Retro groove theme
# "tokyo-night" - Alternative to catppuccin
# "catppuccin-latte" - Light mode, NOT GUARANTEED TO HAVE READABLE TEXT

# You can possibly add custom theme inside styles/patterns
# As long as you follow the variables respectively
name = "catppuccin-mocha"

# Accent of the shell; Hex color only
accent = ""

# Set the background of shell as transparent
transparency = false

[weather]
# Using wttr.in to make this possible

# Enable weather
# Recommend to leave it false to
# avoid getting ratelimited by the service
enable = false
